#!/bin/bash
# Manual deployment instructions for Thomas Hunt Films

echo "📋 MANUAL DEPLOYMENT GUIDE"
echo "=========================="
echo ""
echo "Since SSH keys need to be configured, here are the manual steps:"
echo ""
echo "1️⃣ Connect to server:"
echo "   ssh root@157.230.36.150"
echo ""
echo "2️⃣ Create directories:"
echo "   mkdir -p /var/www/html/1n2.org/thomashuntfilms/videos"
echo "   mkdir -p /var/www/html/1n2.org/thomashuntfilms/press"
echo "   mkdir -p /var/www/html/1n2.org/thunt.net"
echo ""
echo "3️⃣ From LOCAL machine, upload files:"
echo ""
echo "   # Upload homepage"
echo "   scp /Users/curiobot/Sites/1n2.org/index.html root@157.230.36.150:/var/www/html/1n2.org/"
echo ""
echo "   # Upload Thomas Hunt Films"
echo "   scp /Users/curiobot/Sites/1n2.org/thomashuntfilms/index.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/"
echo "   scp /Users/curiobot/Sites/1n2.org/thomashuntfilms/press.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/"
echo "   scp /Users/curiobot/Sites/1n2.org/thomashuntfilms/stolen-channel-story.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/"
echo ""
echo "   # Upload Star Trek video pages"
echo "   scp /Users/curiobot/Sites/1n2.org/thomashuntfilms/videos/*.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/videos/"
echo ""
echo "   # Upload press archive"
echo "   scp -r /Users/curiobot/Sites/1n2.org/thomashuntfilms/press/* root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/press/"
echo ""
echo "4️⃣ Set permissions on server:"
echo "   chown -R www-data:www-data /var/www/html/1n2.org/thomashuntfilms"
echo "   chmod -R 755 /var/www/html/1n2.org/thomashuntfilms"
echo ""
echo "5️⃣ Verify deployment:"
echo "   Visit: https://1n2.org/thomashuntfilms"
echo ""
echo "📦 Files to deploy:"
echo "   ✅ index.html (homepage with new projects)"
echo "   ✅ thomashuntfilms/index.html (38 videos)"
echo "   ✅ thomashuntfilms/press.html (press archive)"
echo "   ✅ thomashuntfilms/stolen-channel-story.html (IG-88 article)"
echo "   ✅ thomashuntfilms/videos/*.html (10 Star Trek pages)"
echo "   ✅ thomashuntfilms/press/* (press article archives)"
echo ""

# Alternative: Try with password auth if available
echo ""
echo "OR use SFTP for GUI upload:"
echo "   Server: sftp://157.230.36.150"
echo "   User: root"
echo "   Remote path: /var/www/html/1n2.org/"
echo ""
