#!/bin/bash
# FINAL DEPLOYMENT SCRIPT
# Run this from your terminal to deploy Thomas Hunt Films

echo "🚀 DEPLOYING THOMAS HUNT FILMS TO PRODUCTION"
echo "=============================================="
echo ""
echo "Server: root@157.230.36.150"
echo "Domain: 1n2.org"
echo ""
echo "This script will deploy:"
echo "  ✅ Updated 1n2.org homepage"
echo "  ✅ Thomas Hunt Films (38 videos)"
echo "  ✅ IG-88 stolen channel article"
echo "  ✅ Press archive (5 articles)"
echo "  ✅ 10 Star Trek video pages"
echo ""
echo "Press ENTER to start deployment (CTRL+C to cancel)"
read

# Change to the correct directory
cd /Users/curiobot/Sites/1n2.org || exit 1

echo ""
echo "Step 1/6: Creating directories on server..."
ssh root@157.230.36.150 "mkdir -p /var/www/html/1n2.org/thomashuntfilms/videos /var/www/html/1n2.org/thomashuntfilms/press" && echo "✅ Directories created" || echo "⚠️  Check if directories already exist"

echo ""
echo "Step 2/6: Uploading homepage..."
scp index.html root@157.230.36.150:/var/www/html/1n2.org/ && echo "✅ Homepage uploaded"

echo ""
echo "Step 3/6: Uploading Thomas Hunt Films main pages (3 files)..."
scp thomashuntfilms/index.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/ && echo "  ✅ index.html"
scp thomashuntfilms/press.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/ && echo "  ✅ press.html"
scp thomashuntfilms/stolen-channel-story.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/ && echo "  ✅ stolen-channel-story.html"
echo "✅ Main pages uploaded"

echo ""
echo "Step 4/6: Uploading Star Trek video pages (10 files)..."
scp thomashuntfilms/videos/*.html root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/videos/ && echo "✅ Video pages uploaded"

echo ""
echo "Step 5/6: Uploading press archive (articles + images)..."
scp -r thomashuntfilms/press/* root@157.230.36.150:/var/www/html/1n2.org/thomashuntfilms/press/ && echo "✅ Press archive uploaded"

echo ""
echo "Step 6/6: Setting permissions..."
ssh root@157.230.36.150 "chown -R www-data:www-data /var/www/html/1n2.org/thomashuntfilms && chmod -R 755 /var/www/html/1n2.org/thomashuntfilms" && echo "✅ Permissions set"

echo ""
echo "=============================================="
echo "🎉 DEPLOYMENT COMPLETE!"
echo "=============================================="
echo ""
echo "🌐 Your sites are now live at:"
echo ""
echo "   📱 Homepage:"
echo "      https://1n2.org"
echo ""
echo "   🎬 Thomas Hunt Films:"
echo "      https://1n2.org/thomashuntfilms"
echo ""
echo "   🤖 IG-88 Stolen Channel Article:"
echo "      https://1n2.org/thomashuntfilms/stolen-channel-story.html"
echo ""
echo "   📰 Press Archive:"
echo "      https://1n2.org/thomashuntfilms/press.html"
echo ""
echo "   📹 Example Video Page:"
echo "      https://1n2.org/thomashuntfilms/videos/star-trek-first-contact.html"
echo ""
echo "📊 Deployment Summary:"
echo "   ✅ 1 homepage updated"
echo "   ✅ 3 main pages deployed"
echo "   ✅ 10 video pages deployed"
echo "   ✅ 5 press articles deployed"
echo "   ✅ 38 total videos showcased"
echo "   ✅ 5.5M views documented"
echo ""
echo "🔍 Next Steps:"
echo "   1. Visit https://1n2.org to see updated homepage"
echo "   2. Click through to Thomas Hunt Films"
echo "   3. Test all navigation links"
echo "   4. Verify YouTube embeds load"
echo "   5. Check press archive images"
echo ""
