var $IE6=navigator.userAgent.match(/msie/i)!=null,$iPd=navigator.userAgent.match(/iPad/i)!=null,$iPh=navigator.userAgent.match(/iPhone/i)!=null,$iPt=navigator.userAgent.match(/iPod/i)!=null;$Andr=(navigator.userAgent.match(/Android/i)!=null)&&($Andr=navigator.userAgent.match(/Mobile/i)!=null);var section=[];var refpage=document.referrer;var editing=0;
function getentries(){for(var a=document.getElementsByTagName("div"),b=0;b<a.length;b++)if(-1!=a[b].className.indexOf("posttitle")||-1!=a[b].className.indexOf("comments"))"none"==document.defaultView.getComputedStyle(a[b],"").getPropertyValue("display")&&b++,section[section.length]=a[b];a=document.getElementsByTagName("h1");for(b=0;b<a.length;b++)-1!=a[b].className.indexOf("posttitle")&&(section[section.length]=a[b]);d=document.getElementsByTagName("h2");for(b=0;b<d.length;b++)-1!=d[b].className.indexOf("posttitle")&&
(section[section.length]=d[b])}
function offsetTop(a){for(var b=0;a;a=a.offsetParent)b+=a.offsetTop;return b}
function getYScroll(){var a;self.pageYOffset?a=self.pageYOffset:document.documentElement&&document.documentElement.scrollTop?a=document.documentElement.scrollTop:document.body&&(a=document.body.scrollTop);return a}
function prevArticle(){var a=50;hasClass(document.getElementsByTagName("header")[0],"closed")&&(a=10);for(var b=getYScroll()-38,e=[],c=section.length;0<=--c;)e[c]=offsetTop(section[c]),mdrn&&(e[c]-=a);e.sort(sortDESC);for(c=0;c<e.length;c++)if(e[c]<b&&0<e[c]){window.scroll(0,e[c]);break}}
function nextArticle(){var a=50;hasClass(document.getElementsByTagName("header")[0],"closed")&&(a=10);for(var b=getYScroll()+38,e=[],c=0;c<section.length;c++)e[c]=offsetTop(section[c]),mdrn&&(e[c]-=a);e.sort(sortASC);for(c=0;c<e.length;c++)if(e[c]>b&&0<e[c]){window.scroll(0,e[c]);break}}
function hasClass(a,b){return-1<(" "+a.className+" ").indexOf(" "+b+" ")};
function highlightPost(s){s.style.background='#FFFFE0';}
function prevPage(){if(refpage!=''){window.location=refpage;}}
function navkey(key){var modifiedKey=false;if(!key)key=window.event;if(!key.target&&!key.srcElement)return;if(key.target&&((key.target.tagName.toLowerCase()=='input')||(key.target.tagName.toLowerCase()=='textarea')))return;if(key.srcElement&&((key.srcElement.tagName.toLowerCase()=='input')||(key.srcElement.tagName.toLowerCase()=='textarea')))return;if((key.metaKey)||(key.shiftKey)||(key.altKey)||(key.ctrlKey))modifiedKey=true;if(key.keyCode)key=key.keyCode;if(typeof section[0]=='undefined')return;if(!modifiedKey){if((key==190)||(key==74))nextArticle();if((key==188)||(key==75))prevArticle();if(key==59)prevPage();if(key==77)$('#shownewcomments').click();}}
function pnhTextareaInsert(a,b,e){if(document.getElementById(a)){a=document.getElementById(a);var s = a.scrollTop;if(document.selection){var d="",c=document.selection.createRange().text,f=c.substring(c.length,c.length-1);if(f==" "){d=" ";c=c.substring(0,c.length-1)}a.focus();document.selection.createRange().text=b+c+e+d}else if(a.selectionStart|a.selectionStart==0){if(a.selectionEnd>a.value.length)a.selectionEnd=a.value.length;d=a.selectionStart;f=a.value.slice(0,a.selectionEnd);f=f.substring(f.length,f.length-1);c=a.selectionEnd+b.length;if((f==" ")&&(a.selectionStart!=a.selectionEnd))c-=1;a.value=a.value.slice(0,d)+b+a.value.slice(d);a.value=a.value.slice(0,c)+e+a.value.slice(c);a.selectionStart=d+b.length;a.selectionEnd=c;a.focus()}a.scrollTop = s;}}
function pnhEditTextarea(d,a){if(document.getElementById(d)){var b="",c="";switch(a){case "backslash":b="/";c="";break;case "gt":b=">";c="";break;case "lt":b="<";c="";break;case "strong":b="<strong>";c="</strong>";break;case "emphasis":b="<em>";c="</em>";break;case "a_href":var e="http://";if(mb||$iPd||$iPh||$Andr)e="";a=prompt("Please enter the site you'd like to link!",e);null!=a&&("http://"!=a&&0<a.length)&&(a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,""),a=a.replace(/"/g,"%22"),a=a.replace(/ /g,"%20"),a=a.replace(/^http:\/\/http:\/\//,"http://"),a=a.replace(/^http:\/\/https:\/\//,"https://"),!/^(ftp|http|https|news|finger|itms|gopher|irc|abp):\/\/.*/.test(a)&&"mailto:"!=a.substring(0,7)&&(a="http://"+a),b='<a href="'+a+'">',c="</a>")}pnhTextareaInsert(d,b,c)}return!1};
function sortASC(a,b){return (a-b);}
function sortDESC(a,b){return (b-a);}
function mouseover(el){el.className="raise";}
function mouseout(el){el.className="buttons";}
function mousedown(el){el.className="press";}
function mouseup(el){el.className="raise";}
function toggleLayer(showId,focusId){if(document.getElementById){var style2=document.getElementById(showId).style;style2.display=style2.display?"":"block";}else if(document.all){var style2=document.all[showId].style;style2.display=style2.display?"":"block";}else if(document.layers){var style2=document.layers[showId].style;style2.display=style2.display?"":"block";}document.getElementById(focusId).focus();return false;}
function sizeModal(){var a=$(window).height(),b=$(window).width()/2,a=a/2-150;244>a&&(a=244);if($iPh||$iPt||$Andr)b=380;$("#lightbox").css("top",a+"px").css("left",b+"px")}function positionModal(){var a=325;if($iPh||$iPt)a=325;$("#lightbox").css("position","absolute").css("top",$(document).scrollTop()+a+"px")}function hideModal(){$("#overlay").hide();$("#lightbox").css("visibility","hidden");$("#lightbox").html("")}
function showModal(){$("#overlay").show();$("#overlay").css({height:$(document).height()});$("#lightbox").show();sizeModal();($IE6||$iPh||$iPt||$iPd)&&positionModal();$("#lightbox").css("visibility","visible").show()}
function init_vid(){$.ajaxSetup({cache:!1});$("a.vid").length&&($("a.vid").click(function(){var a=$(this).attr("href");$("#lightbox").load(a,"",showModal);this.blur();return!1}),$("body").append('<div id="overlay"></div>'),$("body").append('<div id="lightbox"></div>'),Drag.init(document.getElementById("lightbox")),$("#lightbox").css("cursor","move"),$("#overlay").click(function(){$("#overlay").hide();$("#lightbox").css("visibility","hidden");$("#lightbox").html("");this.blur();return!1}),($IE6||$iPh||
$iPt||$iPd)&&$(window).scroll(function(){$("#lightbox").is(":visible")&&positionModal()}))};
function setFlag(c,f){for(c=document.getElementById("flag"+f+c);c.hasChildNodes();)c.removeChild(c.firstChild);c.appendChild(document.createTextNode("[Flagged]"));editing=0}
function cancelFlag(f,h,c){var b=document.createElement("a");b.href="##";b.onclick=function(){flagpost(f,h,c);return!1};b.style.fontWeight="normal";b.target="_self";b.title="Flag this post";b.className="flag";b.innerHTML="!";for(var d=document.getElementById("flag"+c+f);d.hasChildNodes();)d.removeChild(d.firstChild);d.appendChild(document.createTextNode("["));d.appendChild(b);d.appendChild(document.createTextNode("]"));editing=0;return!1}
function flagpost(f,h,c){if(!editing){editing=1;var b=!1;navigator.platform.indexOf("iPhone")!=-1||navigator.platform.indexOf("iPad")!=-1||(b="ontouchstart"in document.documentElement?!0:!1);for(var d=document.getElementById("flag"+c+f);d.hasChildNodes();)d.removeChild(d.firstChild);var a=[],e=[];c==1||c==3||c==5||c==7||c==8||c==10||c==19||c==21||c==23?(a[1]="pick a reason to flag:",e[1]="pick a reason",a[2]="fantastic post",e[2]="fantastic post",a[3]="double post",e[3]="double post",a[4]="HTML/display error",e[4]="display error",a[5]="offensive/sexism/racism",e[5]="offensive/sexism/racism",a[6]="it breaks the guidelines",e[6]="breaks guidelines",a[7]="other",e[7]="other"):(a[1]="pick a reason to flag:",e[1]="pick a reason",a[2]="fantastic comment",e[2]="fantastic comment",a[3]="double comment",e[3]="double comment",a[4]="HTML/display error",e[4]="display error",a[5]="offensive/sexism/racism",e[5]="offensive/sexism/racism",a[6]="noise",e[6]="noise",a[7]="derail",e[7]="derail",a[8]="it breaks the guidelines",e[8]="breaks guidelines",a[9]="other",e[9]="other");var g=document.createElement("select");g.id="reason"+c+f;g.name="badpost_reason";g.font="7px";g.className="flagdrop";g.onchange=function(){this.onblur="";sendFlag(f,h,c)};if(!b)g.onblur=function(){cancelFlag(f,h,c);return!1};for(var i=1;i<a.length;++i){var j=document.createElement("option");j.text=a[i];j.value=e[i];g.options[g.length]=j}d.appendChild(g);a=document.createElement("a");a.href="##";a.style.fontWeight="normal";a.target="_self";a.title="cancel";a.className="flag";a.innerHTML="x";if(b)a.onclick=function(){cancelFlag(f,h,c);return!1};d.appendChild(document.createTextNode(" "));d.appendChild(document.createTextNode("["));d.appendChild(a);d.appendChild(document.createTextNode("]"));document.getElementById("reason"+c+f).focus()}return!1}
function sendFlag(f,h,c){var b=[,"mefi","mefi_comment","ask","ask_comment","metatalk","metatalk_comment","projects","music","music_comment","jobs",,,"projects_comment",,,,,,"irl","irl_comment","exlibris","exlibris_comment","fanfare","fanfare_comment"];var d=document.getElementById("reason"+c+f),a=d.options[d.selectedIndex].value;d.blur();b="badpost_id="+f+"&badpost_type="+b[c];f!=h&&(b=b+"&parent_id="+h);b=b+"&badpost_reason="+escape(a);typeof jQuery=="undefined"?alert("The page is still loading, please wait to flag."):jQuery.post("//"+subd+".metafilter.com/contribute/flag_ajax.cfm",b,setFlag(f,c))};
function warnFav(a,c,b){a=document.getElementById("favmsg"+c+a);a.hasChildNodes()&&a.removeChild(a.firstChild);a.appendChild(document.createTextNode(b?" Removing...":" Adding..."))}
function addFav(a,c,b,d,e,m){typeof jQuery=="undefined"?alert("The page is still loading, please wait to add favorites."):jQuery.ajax({type:"POST",dataType:"text",url:"//"+subd+".metafilter.com/contribute/add_favjax.mefi",data:"link_id="+a+"&parent_id="+c+"&sitetype_id="+b+"&author_id="+d+"&token="+e+"&mob="+m,success:function(f){incFav(f)},beforeSend:warnFav(a,b,0)})}
function delFav(a,c,b,d,e,m){typeof jQuery=="undefined"?alert("The page is still loading, please wait to remove favorites."):jQuery.ajax({type:"POST",dataType:"text",url:"//"+subd+".metafilter.com/contribute/del_favjax.mefi",data:"link_id="+a+"&parent_id="+c+"&sitetype_id="+b+"&author_id="+d+"&token="+e+"&mob="+m,success:function(f){incFav(f)},beforeSend:warnFav(a,b,1)})};
function readCookie(a){a=a+"=";for(var b=document.cookie.split(";"),d=0;d<b.length;d++){for(var c=b[d];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf(a)==0)return c.substring(a.length,c.length)}return null}
function internallinks(){if(!et){var c,d;"%5Fnew"==readCookie("BASE_REF")&&document.getElementById("canonical")&&(c=document.getElementById("canonical").href,c=c.replace(/https?:/gi,""));"https:"==document.location.protocol&&(d=1);if(void 0!=c||void 0!=d)for(var b=document.getElementsByTagName("a"),a=0;a<b.length;++a)if(void 0!=c&&0<=b[a].href.indexOf(c)&&(b[a].target="_self"),void 0!=d&&0<=b[a].href.indexOf("metafilter.com")&&-1==b[a].href.indexOf("ten.metafilter.com")&&-1==b[a].href.indexOf("status.metafilter.com")&&-1==b[a].href.indexOf("shop.metafilter.com")&&
-1==b[a].href.indexOf("mobile.metafilter.com")&&-1==b[a].href.indexOf("stuff.metafilter.com")&&-1==b[a].href.indexOf("playlistpodcast")&&'rss'!==b[a].href.slice(b[a].href.length-3,b[a].href.length))b[a].href=b[a].href.replace(/^http:/gi,"https:")}};
addEvent(window, "load", internallinks);
function showUsername(show){var div=document.getElementById("photouname");if(show==1){div.style.display='block';document.getElementById("photousername").focus();}else{div.style.display='none';document.getElementById("photoinput").focus();}}
function supports_history(){return !!(window.history && history.pushState);} 
function removeJSLinks(){if(!et){$('a[href="http://www.metafilter.com/javascript-required.mefi"]').attr('href','#');}}
(function($,e,b){var c="hashchange",h=document,f,g=$.event.special,i=h.documentMode,d="on"+c in e&&(i===b||i>7);function a(j){j=j||location.href;return"#"+j.replace(/^[^#]*#?(.*)$/,"$1")}$.fn[c]=function(j){return j?this.bind(c,j):this.trigger(c)};$.fn[c].delay=50;g[c]=$.extend(g[c],{setup:function(){if(d){return false}$(f.start)},teardown:function(){if(d){return false}$(f.stop)}});f=(function(){var j={},p,m=a(),k=function(q){return q},l=k,o=k;j.start=function(){p||n()};j.stop=function(){p&&clearTimeout(p);p=b};function n(){var r=a(),q=o(m);if(r!==m){l(m=r,q);$(e).trigger(c)}else{if(q!==m){location.href=location.href.replace(/#.*/,"")+q}}p=setTimeout(n,$.fn[c].delay)}$IE6&&!d&&(function(){var q,r;j.start=function(){if(!q){r=$.fn[c].src;r=r&&r+a();q=$('<iframe tabindex="-1" title="empty"/>').hide().one("load",function(){r||l(a());n()}).attr("src",r||"javascript:0").insertAfter("body")[0].contentWindow;h.onpropertychange=function(){try{if(event.propertyName==="title"){q.document.title=h.title}}catch(s){}}}};j.stop=k;o=function(){return a(q.location.href)};l=function(v,s){var u=q.document,t=$.fn[c].domain;if(v!==s){u.title=h.title;u.open();t&&u.write('<script>document.domain="'+t+'"<\/script>');u.close();q.location.hash=v}}})();return j})()})(jQuery,this);
function isNumber(n) {return !isNaN(parseFloat(n)) && isFinite(n);}
function target(b){$("#triangle").length||$("body").append('<div id="triangle"></div>');if(isNumber(b)){var a=$('a[name="'+b+'"]').next();a.length==0?$("#triangle").css("display","none"):(b=a.offset(),a=parseInt(a.css("margin-left")),a=parseInt(a/2-5),$("#triangle").css("display","inline-block").css("top",b.top).css("left",a))}else b==""&&$("#triangle").css("display","none")};
function init_deltags(){$(".deltag").each(function(){var a=$(this);a.click(function(b){b.preventDefault();$.get(a.attr("href"));a.prev().fadeOut();a.fadeOut("",function(){a.prev().prev().remove()});return!1})})}
function init_addtags(){$("#tagform").submit(function(){var a=$("#taginput").val(),b=$("#lid").val(),c=$("#token").val(),d=$("#authid").val();""==a?(alert("Please enter at least one tag."),$("#taginput").focus()):$.post("/contribute/add_tags.mefi",{js:1,user_id:d,link_id:b,tags:a,token:c},function(a){$("#taglist").html(a);toggleLayer("addtags","taglist");$("#taginput").val("");init_deltags()});return!1});init_deltags()};
function init_editing(){$("div[dtm]").each(function(){var b=$(this),a=Number(b.attr("dtm")),a=a+300,c;$.ajax({type:"GET",async:!1,url:"/contribute/getServerTime.mefi",success:function(a){c=a}});var d=a-Number(c),e=setInterval(function(){0>=d&&(b.fadeOut(),clearInterval(e));d--},1E3)})};
function add_to_ra(a,b){$.post("/contribute/add_to_ra.mefi",{link_id:a,token:b},function(){$("#addra").prop("onclick",null).unbind("click").attr("title","Remove post from Recent Activity").html("remove from activity").click(function(){remove_from_ra(a,b)});$("#addramsg").html(" Added.")}).fail(function(){$("#addramsg").html(" Couldn't add.")})}
function remove_from_ra(a,b){confirm("Are you sure you want to remove this post from Recent Activity?")&&$.post("/contribute/remove_from_ra.mefi",{link_id:a,token:b},function(){$("#addra").prop("onclick",null).unbind("click").attr("title","Add post to Recent Activity").html("add to activity").click(function(){add_to_ra(a,b)});$("#addramsg").html(" Removed.")}).fail(function(){$("#addramsg").html(" Couldn't remove.")})};
var poller={newcomments:0,diff_id:0,comment_id:cid,link_id:lid,failed:0,interval:pint,decay:pdk,last_hash:!1,link_hide:0,link_closed:0,init:function(){var a=window.location.hash;if(this.last_hash!=a&&!this.commentHash()&&-1!=a.indexOf("inline-",1)){var b=a.substr(8);b>this.comment_id&&($.get("/comments-latest.mefi?l="+this.link_id+"&c="+this.comment_id+"&d="+b+"&f=html",function(a){$("#newcomments").append(a).show().trigger("mefi-comments");$("#newcommentsmsg").hide();getentries();init_vid();internallinks();init_editing();target(hash)},"html"),this.diff_id=this.comment_id=b,this.newcomments=0,document.title=btitle)}this.last_hash=a;timeout=setTimeout($.proxy(this.getData,this),this.interval)},getData:function(){var a=this;$.ajax({url:"/comments-latest.mefi?l="+a.link_id+"&c="+a.comment_id+"&f=cnt",dataType:"json",success:function(b){if(1==b[2]||1==b[3])a.failed=20,a.link_hide=b[2],a.link_closed=b[3],a.errorHandler();else if(b[0]==a.newcomments||b[1]==a.diff_id)a.errorHandler();else{a.interval=pint;a.failed=0;a.newcomments=b[0];a.diff_id=b[1];var c="s";"1"==b[0]&&(c="");$("#newcommentsmsg").html(b[0]+" new comment"+c+', <a href="#" id="shownewcomments">show</a>').show();document.title="("+b[0]+") "+btitle;$("#shownewcomments").click(function(){$("#newcommentsmsg").html("Loading...");$.get("/comments-latest.mefi?l="+a.link_id+"&c="+a.comment_id+"&d="+a.diff_id+"&f=html",function(c){$("#newcomments").append(c).show().trigger("mefi-comments");$("#newcommentsmsg").hide();a.commentHash()||(supports_history()?history.replaceState(null,null,window.location.href.split("#")[0]+"#inline-"+b[1]):window.location.hash="inline-"+b[1],a.last_hash="inline-"+b[1]);getentries();init_vid();internallinks();init_editing();target(hash)},"html");a.interval=pint;a.failed=0;a.comment_id=b[1];a.diff_id=b[1];a.newcomments=0;document.title=btitle;return!1});a.init()}},error:$.proxy(a.errorHandler,a)})},errorHandler:function(){++this.failed<pfl?(this.interval*=this.decay,this.init()):(1==this.link_hide?$("#newcommentsmsg").css("background-color","#aa0000").css("border","solid white 1px").css("color","#fff").html("This post was deleted.").show():1==this.link_closed?$("#newcommentsmsg").css("background-color","#333").css("border","solid white 1px").css("color","#fff").html("This post was closed.").show():$("#newcommentsmsg").css("width","500px").html("No recent updates. Reload to check for new comments.").show(),document.title=btitle)},commentHash:function(){var a=window.location.hash;return a&&!isNaN(a.substr(1))?!0:!1}};
var Drag={obj:null,init:function(b,a,c,d,g,e,f,j,h,i){b.onmousedown=Drag.start;b.hmode=f?!1:!0;b.vmode=j?!1:!0;b.root=a&&a!=null?a:b;if(b.hmode&&isNaN(parseInt(b.root.style.left)))b.root.style.left="0px";if(b.vmode&&isNaN(parseInt(b.root.style.top)))b.root.style.top="0px";if(!b.hmode&&isNaN(parseInt(b.root.style.right)))b.root.style.right="0px";if(!b.vmode&&isNaN(parseInt(b.root.style.bottom)))b.root.style.bottom="0px";b.minX=typeof c!="undefined"?c:null;b.minY=typeof g!="undefined"?g:null;b.maxX=typeof d!="undefined"?d:null;b.maxY=typeof e!="undefined"?e:null;b.xMapper=h?h:null;b.yMapper=i?i:null;b.root.onDragStart=new Function;b.root.onDragEnd=new Function;b.root.onDrag=new Function},start:function(b){var a=Drag.obj=this,b=Drag.fixE(b),c=parseInt(a.vmode?a.root.style.top:a.root.style.bottom),d=parseInt(a.hmode?a.root.style.left:a.root.style.right);a.root.onDragStart(d,c);a.lastMouseX=b.clientX;a.lastMouseY=b.clientY;if(a.hmode){if(a.minX!=null)a.minMouseX=b.clientX-d+a.minX;if(a.maxX!=null)a.maxMouseX=a.minMouseX+a.maxX-a.minX}else{if(a.minX!=null)a.maxMouseX=-a.minX+b.clientX+d;if(a.maxX!=null)a.minMouseX=-a.maxX+b.clientX+d}if(a.vmode){if(a.minY!=null)a.minMouseY=b.clientY-c+a.minY;if(a.maxY!=null)a.maxMouseY=a.minMouseY+a.maxY-a.minY}else{if(a.minY!=null)a.maxMouseY=-a.minY+b.clientY+c;if(a.maxY!=null)a.minMouseY=-a.maxY+b.clientY+c}document.onmousemove=Drag.drag;document.onmouseup=Drag.end;return!1},drag:function(b){var b=Drag.fixE(b),a=Drag.obj,c=b.clientY,b=b.clientX,d=parseInt(a.vmode?a.root.style.top:a.root.style.bottom),g=parseInt(a.hmode?a.root.style.left:a.root.style.right),e,f;a.minX!=null&&(b=a.hmode?Math.max(b,a.minMouseX):Math.min(b,a.maxMouseX));a.maxX!=null&&(b=a.hmode?Math.min(b,a.maxMouseX):Math.max(b,a.minMouseX));a.minY!=null&&(c=a.vmode?Math.max(c,a.minMouseY):Math.min(c,a.maxMouseY));a.maxY!=null&&(c=a.vmode?Math.min(c,a.maxMouseY):Math.max(c,a.minMouseY));e=g+(b-a.lastMouseX)*(a.hmode?1:-1);f=d+(c-a.lastMouseY)*(a.vmode?1:-1);a.xMapper?e=a.xMapper(d):a.yMapper&&(f=a.yMapper(g));Drag.obj.root.style[a.hmode?"left":"right"]=e+"px";Drag.obj.root.style[a.vmode?"top":"bottom"]=f+"px";Drag.obj.lastMouseX=b;Drag.obj.lastMouseY=c;Drag.obj.root.onDrag(e,f);return!1},end:function(){document.onmousemove=null;document.onmouseup=null;Drag.obj.root.onDragEnd(parseInt(Drag.obj.root.style[Drag.obj.hmode?"left":"right"]),parseInt(Drag.obj.root.style[Drag.obj.vmode?"top":"bottom"]));Drag.obj=null},fixE:function(b){if(typeof b=="undefined")b=window.event;return b}};
document.onkeydown=navkey;window.onload=getentries;
$(document).ready(function(){removeJSLinks()});