// CURIO ARCHIVE - COMPLETE DATA
// The definitive encyclopedia of Curio Cards

const CURIO_DATA = {
  
  // ===================
  // ALL 31 CARDS (1-30 + 17b)
  // ===================
  
  cards: [
    {
      number: 1,
      title: "Apples",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 191,
      issued: 1809,
      locked: 0,
      mintDate: "2017-05-09",
      releaseWeek: 1,
      set: "Story Set",
      description: "The first art NFT on Ethereum. Hunt had an English Literature background and has said the Apple is meant to represent the fall from grace in the story of Adam and Eve, plus Apple computer. It started with an A, making it fitting that it was the first card released in the set.",
      significance: "First Art NFT on Ethereum",
      imageUrl: "images/01.jpg",
      ipfsHash: "QmfXYgfBYJiDRe1YYiTDADt3TXGPCrYhAx4DnJhfNr1D9b",
    },
    {
      number: 2,
      title: "Nuts",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 370,
      issued: 1630,
      locked: 0,
      mintDate: "2017-05-09",
      releaseWeek: 1,
      set: "Story Set",
      description: "The Nuts and Berries are grouped together intentionally, as they represent sustenance, and reference lyrics from a Talking Heads song. Part of the narrative of humanity's evolution into art creators.",
      significance: "Part of the foundational Story Set",
      imageUrl: "images/02.jpg",
      ipfsHash: "QmYvCfMHRt8W5c3HKt9QBwjM12Y28bGXn7KP3V7fvDHv2u",
    },
    {
      number: 3,
      title: "Berries",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 416,
      issued: 1584,
      locked: 0,
      mintDate: "2017-05-09",
      releaseWeek: 1,
      set: "Story Set",
      description: "Completes the sustenance theme with Nuts. References Talking Heads lyrics and represents the beginning of humanity's journey toward creating art.",
      significance: "Part of the foundational Story Set",
      imageUrl: "images/03.jpg",
      ipfsHash: "QmXjMNHfGFUchsNaYY9uB8PDZxmQQRsJCqPRbSzMNYWkPp",
    },    {
      number: 4,
      title: "Clay",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 1540,
      issued: 460,
      locked: 0,
      mintDate: "2017-05-16",
      releaseWeek: 2,
      set: "Story Set",
      description: "Clay starts the new series of cards that represent the building blocks of art. It's also the first card on the list with a significantly lower supply.",
      significance: "First card with reduced supply",
      imageUrl: "images/04.jpg",
      ipfsHash: "QmXm2fCVqPjXqT6BtaVyV7wqhErvFZy4V2aKjWkRW7XPUe",
    },
    {
      number: 5,
      title: "Paint",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 1562,
      issued: 438,
      locked: 0,
      mintDate: "2017-05-16",
      releaseWeek: 2,
      set: "Story Set",
      description: "Paint continues the trend of representing the building blocks of art and offers an even smaller supply.",
      significance: "Building block of art theme",
      imageUrl: "images/05.jpg",
      ipfsHash: "QmfXcGqbVSdGC5N8SJhQLx1ZEHj8BoqZxNqsZZJ3Dc2DyS",
    },
    {
      number: 6,
      title: "Ink",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 1562,
      issued: 438,
      locked: 0,
      mintDate: "2017-05-16",
      releaseWeek: 2,
      set: "Story Set",
      description: "Ink is part of the same theme as the two cards that precede it — the building blocks of art.",
      significance: "Building block of art theme",
      imageUrl: "images/06.jpg",
      ipfsHash: "QmQp5RhRcTwwHvKKEPmQrHWWQprFmRxeVW7JQCGBvXS8tQ",
    },
    {
      number: 7,
      title: "Sculpture",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2135,
      burned: 135,
      issued: 2000,
      locked: 135,
      mintDate: "2017-05-23",
      releaseWeek: 3,
      set: "Story Set",
      description: "Sculpture is the first art in the series that represents what can be made with art building blocks (clay). Transitions from materials to creations.",
      significance: "First artistic creation in the story",
      imageUrl: "images/07.jpg",
      ipfsHash: "QmNq3VmKsWuwCPEJJoaM4D3QbzWFVgNqBe8XNJCDyQAJYj",
    },
    {
      number: 8,
      title: "Painting",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 0,
      mintDate: "2017-05-23",
      releaseWeek: 3,
      set: "Story Set",
      description: "The painting, depicting Mona Lisa, ties to card 5 (paint) and represents the art you can create with paint. Possibly the first Mona Lisa on the blockchain.",
      significance: "First representation of classical art on blockchain",
      imageUrl: "images/08.jpg",
      ipfsHash: "QmYLBV6BYYFWqMghLQDVDwNCGfKsK4nYJBKSdHMCKVMRwz",
    },
    {
      number: 9,
      title: "Book",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 183,
      mintDate: "2017-05-23",
      releaseWeek: 3,
      set: "Story Set",
      description: "The book art card matches to card 6, ink. It represents what can be created with ink.",
      significance: "Completes the creation theme",
      imageUrl: "images/09.jpg",
      ipfsHash: "QmcAcAg8JJvBdJTv9j6U4QRLvmM3KXMM6mLd2LbN3Sxaop",
    },
    {
      number: 10,
      title: "Future",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 0,
      mintDate: "2017-05-30",
      releaseWeek: 4,
      set: "Story Set",
      description: "Card 10 represents the future and going down the road of the artist's journey. The first 10 cards set the stage for sustenance, tools to create art, the creations themselves, and now heading toward the future of art.",
      significance: "Conclusion of the Story Set narrative",
      imageUrl: "images/10.jpg",
      ipfsHash: "QmPrq8yd1n3rqjYMLHzJhbHPT5CQ8bQnK7MdL5X7Q5Ezo7",
    },    {
      number: 11,
      title: "BTC Keys",
      artist: "Cryptograffiti",
      artistSlug: "cryptograffiti",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 0,
      mintDate: "2017-06-06",
      releaseWeek: 5,
      set: "Bitcoin Propaganda",
      description: "This is the first card in the collection created by Cryptograffiti, one of the most prolific Bitcoin artists. This card kicks off the Bitcoin Propaganda set. This art is in reference to the UBS logo.",
      significance: "First card by Cryptograffiti",
      imageUrl: "images/11.jpg",
      ipfsHash: "QmPRoE1fqNjPfQ6hQURAZL7J8S7HuTkC5mBRnQu5qo3b8H",
    },
    {
      number: 12,
      title: "Mine Bitcoin",
      artist: "Cryptograffiti",
      artistSlug: "cryptograffiti",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 163,
      mintDate: "2017-06-06",
      releaseWeek: 5,
      set: "Bitcoin Propaganda",
      description: "Depicts a rendition of the MasterCard logo. Cryptograffiti used to put these logos on neighborhood ATMs as street art activism. 'Repurposing banking materials has remained a theme in my work,' he said.",
      significance: "Street art activism meets blockchain",
      imageUrl: "images/12.jpg",
      ipfsHash: "QmVfZPg5cFxLbBgfKqB81U7S8FYXMKkHvXKP5fj5khgWPY",
    },
    {
      number: 13,
      title: "BTC",
      artist: "Cryptograffiti",
      artistSlug: "cryptograffiti",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 0,
      mintDate: "2017-06-06",
      releaseWeek: 5,
      set: "Bitcoin Propaganda",
      description: "This art is based on the Citi logo. 'I used to put these logos on neighborhood ATMs. Repurposing banking materials has remained a theme in my work. I like the idea of using soon-to-be-extinct items to help spread the new cryptocurrency movement.' — Cryptograffiti",
      significance: "Anti-banking activism through art",
      imageUrl: "images/13.jpg",
      ipfsHash: "QmWXJLWFybpAGYSqd8c5SrwGYxDNWX5QE7bRABvYNFP6zb",
    },
    {
      number: 14,
      title: "CryptoCurrency",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-06-13",
      releaseWeek: 6,
      set: "Brand Mashups",
      description: "This art inserts Cryptocurrency into a globally recognized Coca-Cola logo. Phneep created a lot of Bitcoin movie posters which can be found on his website.",
      significance: "First low-supply card (500)",
      imageUrl: "images/14.jpg",
      ipfsHash: "QmYzNfPGZPNbDHST1ShHJv9eAJz1V9BYqLhVwVRW8CQbkf",
    },
    {
      number: 15,
      title: "DigitalCash",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-06-13",
      releaseWeek: 6,
      set: "Brand Mashups",
      description: "This art inserts Cryptocurrency into a globally recognized Wendy's logo. Part of the corporate brand subversion series.",
      significance: "Corporate logo subversion",
      imageUrl: "images/15.jpg",
      ipfsHash: "QmYJfU8AqBBJLgG4pBk5t6PCNEABrqBt2bDmShQfMVW4DY",
    },
    {
      number: 16,
      title: "OriginalCoin",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-06-13",
      releaseWeek: 6,
      set: "Brand Mashups",
      description: "This art inserts Cryptocurrency into a globally recognized Heineken logo and completes the set of food and beverage-inspired art cards. There's a reference to 'open source' in the art, highlighting one of the most attractive qualities of cryptocurrency.",
      significance: "Open source philosophy in consumer branding",
      imageUrl: "images/16.jpg",
      ipfsHash: "QmTRoEVnBqQRGH6eHZexQCZNxZZDPc35TBfXj6QCvDBLLf",
    },
    {
      number: 17,
      title: "UASF",
      artist: "Cryptopop",
      artistSlug: "cryptopop",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 8,
      mintDate: "2017-06-20",
      releaseWeek: 7,
      set: "Crypto Memes",
      description: "On August 1st, 2017 a proposal to scale bitcoin was deployed. UASF stands for User-activated soft fork. Luis, the artist, was celebrating UASF, the protocol deployed to help scale bitcoin. Community consensus was required for changes to the blockchain and there was much debate about this introduction.",
      significance: "First dog on Ethereum, documents Bitcoin scaling debate",
      imageUrl: "images/17.jpg",
      ipfsHash: "QmYvp1H6YBqxRxJNWUFaKd4bYYYm89qFqGv1JLGbAj7ZJN",
    },
    {
      number: "17b",
      title: "UASF (Misprint)",
      artist: "Cryptopop",
      artistSlug: "cryptopop",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-06-20",
      releaseWeek: 7,
      set: "Crypto Memes",
      description: "The #17 card was discovered on an alternative contract, which meant that there were actually two functioning number 17 cards. Hunt said that people were able to buy the 'error' card and lots of people wanted it to be part of the set. During deployment, something went wrong with the contract. The erroneous contract was briefly live before anyone realized the mistake. One collector managed to acquire copies before the contract was disabled. This misprint is now considered an integral part of a 'full set.'",
      significance: "Legendary misprint, only 31st card in collection",
      imageUrl: "images/17b.png",
      ipfsHash: "QmYXM8HvXy8j5G7xByFLPJbBvQBYNQ8VxRQ1j7jqYWqpQy",
    },
    {
      number: 18,
      title: "To The Moon",
      artist: "Cryptopop",
      artistSlug: "cryptopop",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 8,
      mintDate: "2017-06-27",
      releaseWeek: 8,
      set: "Crypto Memes",
      description: "Captures the now very recognizable 'to the moon!' phrase, signaling a change in how people view currency and its future.",
      significance: "Immortalizes crypto culture meme",
      imageUrl: "images/18.jpg",
      ipfsHash: "QmTNvFgjvQM3WqZY8T2UWkJY6L6X4C7Lx1x7hVNBgJqC6g",
    },
    {
      number: 19,
      title: "Dogs Trading",
      artist: "Cryptopop",
      artistSlug: "cryptopop",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-06-27",
      releaseWeek: 8,
      set: "Crypto Memes",
      description: "Features dogs sitting at a poker table. If you look closely you can see references to the ICO boom in 2017. A dog passing Monero under the table, and each coin has a label referencing 2017 coins (some still functioning today, others aren't).",
      significance: "Documents ICO boom era",
      imageUrl: "images/19.jpg",
      ipfsHash: "QmQjYP5eWZM2vjCHvXU1gMf8gJU6wKjL9gWPNqVmCPfA7V",
    },
    {
      number: 20,
      title: "Mad Bitcoins",
      artist: "Phneep",
      artistSlug: "phneep",
      supply: 2000,
      burned: 0,
      issued: 2000,
      locked: 453,
      mintDate: "2017-07-04",
      releaseWeek: 9,
      set: "Special",
      description: "This card depicts MadBitcoins (Thomas Hunt) head on James Bond's body. Initially, this card was supposed to raise money for MadBitcoins but it didn't work. Mad Bitcoins had a popular YouTube show and is one of the founders of Curio Cards.",
      significance: "First portrait on Ethereum",
      imageUrl: "images/20.jpg",
      ipfsHash: "QmYFXPqgMx4MPnLzPkQm3jMcxQ1qU5jgx1cKNKxQM3QZuP",
    },    {
      number: 21,
      title: "The Wizard",
      artist: "Robek World",
      artistSlug: "robek-world",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-07-11",
      releaseWeek: 10,
      set: "RPG Founders",
      description: "This is the first art in this set created by Robek World, who got selected as an artist after creating a gallery for the founders to be a part of the project. When Robek's cards were released, he couldn't even buy them. The Wizard is the persona of Thomas Hunt, and it's a play on video game avatars. Robek was an early supporter of Curio Cards and didn't need convincing to produce art for the project. He even created a commercial for the three cards in his set.",
      significance: "Part of RPG founder tribute series",
      imageUrl: "images/21.png",
      ipfsHash: "QmPJj4p5rY8VGUMbQ8EH1cXPHtKnJ4NNvLxJXD5vhDYd3B",
    },
    {
      number: 22,
      title: "The Bard",
      artist: "Robek World",
      artistSlug: "robek-world",
      supply: 500,
      burned: 0,
      issued: 500,
      locked: 0,
      mintDate: "2017-07-11",
      releaseWeek: 10,
      set: "RPG Founders",
      description: "This card is unique because it is the only one in the set with the number on the right side of the card. It represents a song-singing leader, inspired by co-creator Travis Uhrig.",
      significance: "Only card with number on right side",
      imageUrl: "images/22.png",
      ipfsHash: "QmWp9jHGTQhLVVQWF1PkYWqxmqNFVrLbBhGdQkWHvY6dX9",
    },
    {
      number: 23,
      title: "The Barbarian",
      artist: "Robek World",
      artistSlug: "robek-world",
      supply: 250,
      burned: 0,
      issued: 250,
      locked: 0,
      mintDate: "2017-07-11",
      releaseWeek: 10,
      set: "RPG Founders",
      description: "A two-frame GIF depicting co-founder Rhett Creighton as a flexing, winking warrior. Robek chose the supply of his cards and intentionally reduced card 23 to a supply of 250 because he foresaw collectors wanting all 3 cards in his set. It incentivized people to quickly buy this card so that they could complete the set - turns out he was right and his set sold out.",
      significance: "First animated NFT on Ethereum, first card to sell out",
      imageUrl: "images/23.gif",
      ipfsHash: "QmajJqdpSfqPzQM9m3YhUZc2D3v8T8QZH7z5YxZNPUFp6Y",
    },
    {
      number: 24,
      title: "Complexity",
      artist: "Daniel Friedman",
      artistSlug: "daniel-friedman",
      supply: 333,
      burned: 0,
      issued: 333,
      locked: 0,
      mintDate: "2017-07-18",
      releaseWeek: 11,
      set: "Hand-Drawn Patterns",
      description: "Daniel Friedman shared hand-drawn art on his Flickr account and was brought on board after the founding team discovered it. He's currently a researcher in entomology and it was said that he had a great attitude toward his art and spreading it like a hobby. This art is special because it brought physical artwork to the digital space.",
      significance: "First physical art brought to digital blockchain",
      imageUrl: "images/24.jpg",
      ipfsHash: "QmWwpGNqcLqj4PaKVkdX4CpFKoqh8GJMpNzNGxY4qNfBLy",
    },
    {
      number: 25,
      title: "Passion",
      artist: "Daniel Friedman",
      artistSlug: "daniel-friedman",
      supply: 222,
      burned: 0,
      issued: 222,
      locked: 0,
      mintDate: "2017-07-25",
      releaseWeek: 12,
      set: "Hand-Drawn Patterns",
      description: "What's interesting about this set by Daniel Friedman is that the supply was released as follows: 333 copies, 222 copies, 111 copies. Friedman had a positive attitude toward his art and treated it like a hobby. The way the supply was released reflects this playfulness toward the art.",
      significance: "Part of decreasing supply pattern (333→222→111)",
      imageUrl: "images/25.jpg",
      ipfsHash: "QmUxKNzLMWH3jPPCkZJFYFxJyLgYJY8q1aqCGWqJJQy2YA",
    },
    {
      number: 26,
      title: "Education",
      artist: "Daniel Friedman",
      artistSlug: "daniel-friedman",
      supply: 111,
      burned: 0,
      issued: 111,
      locked: 5,
      mintDate: "2017-08-01",
      releaseWeek: 13,
      set: "Hand-Drawn Patterns",
      description: "The rarest card in the entire set. After the 333, 222, and 111 supply releases, plus 5 locked copies of this card, only 106 complete copies exist. Because of this card's supply of 111, there can never be more than 111 complete sets of Curio Cards.",
      significance: "Rarest card, limits complete sets to maximum 111",
      imageUrl: "images/26.jpg",
      ipfsHash: "QmVVcvNJ7PQxG1Kh4KJbYJpG2Gzc1yC5hLQBNd5F8HXqZ7",
    },
    {
      number: 27,
      title: "Blue",
      artist: "Marisol Vengas",
      artistSlug: "marisol-vengas",
      supply: 600,
      burned: 0,
      issued: 600,
      locked: 35,
      mintDate: "2017-08-08",
      releaseWeek: 14,
      set: "Subverted Fine Art",
      description: "The Blue card starts us off on a set created by Marisol Vengas meant to represent fine art. Marisol Vengas is an anonymous artist collective lead by Max Infield from Northern California. These cards took real-world photography and layered in artistic design on top of it. Artists worked in stations and collaborated to produce these through 'community algorithm' sessions.",
      significance: "First collaborative NFT art",
      imageUrl: "images/27.jpg",
      ipfsHash: "QmZf4E6f8M8tZnLCGLQxqe4o5qiXLNxN7gQGYCx8XqMrfr",
    },
    {
      number: 28,
      title: "Pink",
      artist: "Marisol Vengas",
      artistSlug: "marisol-vengas",
      supply: 400,
      burned: 0,
      issued: 400,
      locked: 0,
      mintDate: "2017-08-08",
      releaseWeek: 14,
      set: "Subverted Fine Art",
      description: "This is the second card in the fine art set with a slightly lower supply than the blue card. Like card 27, this features a real-world photograph with art layered on top of it.",
      significance: "Collaborative fine art series",
      imageUrl: "images/28.jpg",
      ipfsHash: "QmR7vU7WqzpD3bjGJJXG4r6CaHMgE4ZgYwX7xXqRXC9jPV",
    },
    {
      number: 29,
      title: "Yellow",
      artist: "Marisol Vengas",
      artistSlug: "marisol-vengas",
      supply: 200,
      burned: 0,
      issued: 200,
      locked: 0,
      mintDate: "2017-08-08",
      releaseWeek: 14,
      set: "Subverted Fine Art",
      description: "This is the rarest fine art card in the set with a supply of just 200.",
      significance: "Rarest collaborative art piece",
      imageUrl: "images/29.jpg",
      ipfsHash: "QmQcXQpTRk1aLZQcw9VHFqZX4MbHPqVG7KUXe7o7SXCPaR",
    },
    {
      number: 30,
      title: "Eclipse",
      artist: "Thoros of Myr",
      artistSlug: "thoros-of-myr",
      supply: 821,
      burned: 0,
      issued: 821,
      locked: 5,
      mintDate: "2017-08-21",
      releaseWeek: 15,
      set: "Eclipse",
      description: "This is the only card in the set that was released on the day of the Great American Eclipse. Cards were typically released on Tuesdays, but this card finishes the set and was based on that eclipse on August 21st, 2017 (occurred on a Monday). The supply of this card is 821, which represents the date of the eclipse, 8/21. The artist who created card 30 is very private and wishes to remain anonymous even to this day.",
      significance: "Final card, released on eclipse day, anonymous artist",
      imageUrl: "images/30.gif",
      ipfsHash: "QmZLBnJ4dJpE1xQxG7NvSVGVgJ8G7zDPh5KxfYoN5B7Qbx",
    },
  ],

  // ===================
  // ARTISTS
  // ===================
  
  artists: [
    {
      slug: "phneep",
      name: "Phneep",
      realName: "Unknown",
      bio: "Phneep created the first 10 cards of the Curio Cards collection, known as the 'Story Set.' His work tells a narrative of humanity's evolution as art creators, moving from sustenance (apples, nuts, berries) to the building blocks of art (clay, paint, ink) to artistic creations (sculpture, painting, book) and finally to the future. Phneep brought a literary and conceptual approach to the collection, with each card carefully positioned in a larger story arc. He also contributed the brand mashup series (cards 14-16) and the Mad Bitcoins tribute (card 20). His work on Curio Cards showcased his broader practice of creating Bitcoin propaganda and movie poster mashups.",
      cards: [1,2,3,4,5,6,7,8,9,10,14,15,16,20],
      website: "https://www.phneep.com/",
      twitter: "@phneep",
      notableWorks: "Bitcoin movie posters, brand propaganda art",
      contribution: "Created the foundational Story Set and brand mashups",
    },
    {
      slug: "cryptograffiti",
      name: "Cryptograffiti",
      realName: "Unknown",
      bio: "Cryptograffiti is one of the most prolific Bitcoin street artists. Before Curio Cards, he was known for creating Bitcoin-themed stickers and placing them on bank ATMs around San Francisco as a form of activism. His work repurposes banking materials and corporate logos to spread the cryptocurrency movement. 'I used to put these logos on neighborhood ATMs. Repurposing banking materials has remained a theme in my work. I like the idea of using soon-to-be-extinct items to help spread the new cryptocurrency movement.' His three cards for Curio (11-13) continue this theme of subverting financial institution logos - UBS becomes BTC Keys, MasterCard becomes Mine Bitcoin, and Citibank becomes BTC.",
      cards: [11,12,13],
      website: "https://cryptograffiti.com/",
      twitter: "@cryptograffiti",
      notableWorks: "Bitcoin street art, physical crypto art installations",
      contribution: "Bitcoin propaganda series, street art activism",
    },
    {
      slug: "cryptopop",
      name: "Cryptopop",
      realName: "Luis Buenaventura",
      bio: "Cryptopop (Luis Buenaventura) contributed the 'crypto memes' cards to the collection - featuring the first dogs on Ethereum and capturing the culture of early cryptocurrency. His UASF card (17) celebrated the User-Activated Soft Fork protocol deployed to help scale Bitcoin, documenting an important moment in blockchain governance. The card's contract error created the legendary 17b misprint. His 'To The Moon' card immortalized what would become one of crypto's most enduring phrases. 'Dogs Trading' captures the ICO boom of 2017 with hidden details like a dog passing Monero under the table and each coin labeled with references to 2017-era cryptocurrencies.",
      cards: [17,"17b",18,19],
      website: null,
      twitter: "@helloluis",
      notableWorks: "Early crypto meme art",
      contribution: "First dogs on Ethereum, crypto culture documentation",
    },
    {
      slug: "robek-world",
      name: "Robek World",
      realName: "Unknown",
      bio: "Robek World was an early supporter of Curio Cards who created a gallery for the founders and was selected to contribute art to the project. Growing up collecting Japanese anime off dial-up internet, he understood the power of animation and visual storytelling. He wanted to create elaborate, animated pixel art - RPG-inspired characters with fluid movement. But blockchain technology in 2017 wasn't ready for that. He was forced to create what the technology would allow: a two-frame GIF. Card #23, The Barbarian, became the first animated NFT on the Ethereum blockchain. His three cards depict the founders as RPG archetypes: Thomas Hunt as The Wizard, Travis Uhrig as The Bard, and Rhett Creighton as The Barbarian. Strategically, he halved the supply of The Barbarian to 250, foreseeing collectors would want all three. The Barbarian was the first card in the entire collection to sell out. He even created a commercial for his three-card set.",
      cards: [21,22,23],
      website: null,
      twitter: "@robek_world",
      notableWorks: "First animated NFT on Ethereum",
      contribution: "RPG founder tributes, first animation on blockchain",
    },
    {
      slug: "daniel-friedman",
      name: "Daniel Friedman",
      realName: "Daniel Friedman",
      bio: "Daniel Friedman is a researcher in entomology who shared intricate hand-drawn ink patterns on his Flickr account. The founding team discovered his work and brought him on board. He had a great attitude toward his art and spreading it like a hobby. His work is special because it brought physical artwork to the digital space - each pattern was freehand drawn, mostly during classes, with ink on paper. From 2008 to 2014 he only drew in black & white, then began using some colors, mainly red. His three cards feature a playfully decreasing supply pattern (333→222→111) that reflects his experimental approach. Card #26 'Education' with only 111 copies became the rarest card in the set, limiting complete collections to a maximum of 111 sets forever.",
      cards: [24,25,26],
      website: null,
      flickr: "https://www.flickr.com/photos/daniel_friedman/",
      twitter: null,
      notableWorks: "Hand-drawn ink patterns",
      contribution: "Brought physical art to blockchain, created rarest card",
    },
    {
      slug: "marisol-vengas",
      name: "Marisol Vengas",
      realName: "Max Infield (collective)",
      bio: "Marisol Vengas is an anonymous artist collective originating from Northern California, led by Max Infield of Chico, California. The collective operates in what's been described as an 'AI-induced hive mindset.' Works are produced by over a dozen artists who have never met in real life, discovering each other from forums and online groups. None of them know how they've been selected to participate. The artists don't know who they get the pieces from or where they end up. The three Curio Cards (27-29) feature real-world photography with artistic design layered on top. Artists worked in stations through 'community algorithm' sessions at coffee shops to collaboratively produce the work. This made Marisol Vengas's cards the first truly collaborative NFT art on Ethereum.",
      cards: [27,28,29],
      website: null,
      twitter: null,
      notableWorks: "Collaborative fine art, community algorithm sessions",
      contribution: "First collaborative NFT art, subverted fine art photography",
    },
    {
      slug: "thoros-of-myr",
      name: "Thoros of Myr",
      realName: "Unknown (Anonymous)",
      bio: "Thoros of Myr is the most mysterious artist in the Curio Cards collection. The artist wishes to remain completely anonymous even to this day. Created only one card for the collection - #30 'Eclipse' - which was released on August 21, 2017, the day of the Great American Eclipse. Cards were typically released on Tuesdays, but this special card was released on a Monday to coincide with the eclipse. The supply of 821 cards represents the date: 8/21. This final card completed the original Curio Cards collection and remains shrouded in mystery, with the artist's identity unknown even to the founders and community.",
      cards: [30],
      website: null,
      twitter: null,
      notableWorks: "Eclipse card",
      contribution: "Final card, eclipse commemoration, maintained complete anonymity",
    },
  ],

  // ===================
  // FOUNDERS
  // ===================
  
  founders: [
    {
      name: "Thomas Hunt",
      alias: "Mad Bitcoins",
      role: "Co-Founder, Conceptualist",
      bio: "Thomas Hunt, known online as Mad Bitcoins, is a Bitcoin YouTuber with an English Literature background who had always loved baseball trading cards. When he met Travis Uhrig at a Bitcoin meetup in San Francisco, he had a revelation: why not combine his love for cryptocurrency with his love for collecting? The idea was simple but revolutionary — create digital trading cards that lived on the blockchain. Hunt organized the 'Proof of Art' Bitcoin art show in 2016 with Uhrig, which inspired the creation of Curio Cards. He provided the conceptual vision and narrative structure, particularly influencing the Story Set cards. He appears as 'The Wizard' in card #21 and as himself in the Mad Bitcoins tribute card #20.",
      contribution: "Conceptual vision, narrative design",
      cardAppearances: [20, 21],
      social: "@MadBitcoins",
    },
    {
      name: "Travis Uhrig",
      alias: null,
      role: "Co-Founder, Software Developer",
      bio: "Travis Uhrig is a software developer who met Thomas Hunt at a Bitcoin meetup in San Francisco. Together they organized the 'Proof of Art' show in 2016, which confirmed their vision that digital art and blockchain were meant for each other. Uhrig played a crucial role in the technical implementation and artist recruitment. He brought on Rhett Creighton as the technical lead. Interestingly, Uhrig himself didn't even have a complete set of Curio Cards. He appears as 'The Bard' in card #22, depicted as a song-singing leader.",
      contribution: "Technical implementation, artist coordination",
      cardAppearances: [22],
      social: null,
    },
    {
      name: "Rhett Creighton",
      alias: null,
      role: "Lead Developer",
      bio: "Rhett Creighton is a cryptocurrency developer who was recruited as the 'tech muscle' behind Curio Cards. He originally suggested building their own version of Ethereum for the cards, but Uhrig pointed out this would leave the project orphaned on its own chain. They stayed on the public Ethereum blockchain - a prescient decision. Creighton developed the smart contracts and handled all the technical deployment. During the deployment of Card #17, something went wrong with the contract, creating the legendary 17b misprint. He appears as 'The Barbarian' in card #23, the first animated NFT on Ethereum.",
      contribution: "Smart contract development, technical architecture",
      cardAppearances: [23],
      social: null,
    },
  ],

  // ===================
  // TIMELINE
  // ===================
  
  timeline: [
    {
      date: "2016",
      title: "Proof of Art Show",
      text: "Thomas Hunt and Travis Uhrig organize a Bitcoin art show in San Francisco called 'Proof of Art.' Cryptograffiti exhibits art. The event inspires the idea of putting art on the blockchain.",
      type: "origin",
      importance: "high"
    },
    {
      date: "Early 2017",
      title: "Concept & Development",
      text: "Hunt, Uhrig, and newly recruited developer Rhett Creighton begin building Curio Cards on Ethereum. They choose Ethereum over Bitcoin because of smart contract capabilities. Creighton originally suggested making their own chain, but Uhrig convinced them to stay on public Ethereum.",
      type: "origin",
      importance: "high"
    },
    {
      date: "May 9, 2017",
      title: "Launch Day - First Art NFTs on Ethereum",
      text: "Curio Cards launches with the first three cards by Phneep: Apples, Nuts, and Berries. Cards cost $1 each, with 100% of revenue going to artists. Card #1 Apples becomes the first art NFT on Ethereum, predating CryptoPunks by six weeks.",
      type: "launch",
      importance: "critical"
    },
    {
      date: "May–Aug 2017",
      title: "Weekly Card Releases",
      text: "New cards are released weekly. Three cards per week, with exceptions for Cards 10, 20, and 30 (released solo). For Cards 1-10, supply was set at 100,000 with unsold cards burned after each week (typically 2,000 sold, 98,000 burned). Artists choose supply for Cards 11-30.",
      type: "release",
      importance: "medium"
    },
    {
      date: "June 20, 2017",
      title: "The 17b Misprint",
      text: "During the deployment of Card #17 (UASF), something goes wrong with the contract. The misprint is briefly available before being disabled. One collector manages to acquire copies, creating what will become a legendary artifact. The community later decides 17b should be part of the canonical collection.",
      type: "notable",
      importance: "high"
    },
    {
      date: "July 4, 2017",
      title: "First Animated NFT on Ethereum",
      text: "Robek World's Card #23 (The Barbarian) is released as a two-frame GIF — the first animated NFT on Ethereum. It becomes the first card to sell out. Robek strategically reduced its supply to 250 to create scarcity.",
      type: "milestone",
      importance: "critical"
    },
    {
      date: "July 4, 2017",
      title: "First Portrait on Ethereum",
      text: "Card #20 (Mad Bitcoins) depicting founder Thomas Hunt is released, becoming the first portrait NFT on Ethereum.",
      type: "milestone",
      importance: "high"
    },
    {
      date: "August 21, 2017",
      title: "Eclipse / Collection Complete",
      text: "Card #30 (Eclipse) by Thoros of Myr is released on the day of the Great American Eclipse, completing the collection. Supply is set to 821 (the date 8/21). The collection is now fully minted: 30 cards + 17b. Total of 29,700 cards minted. No more can ever be created.",
      type: "milestone",
      importance: "critical"
    },
    {
      date: "2017–2020",
      title: "The Quiet Years",
      text: "The NFT market is virtually nonexistent. Cards trade for 25 cents to $1. The Curio Cards website goes quiet, but the smart contracts remain active on Ethereum. Most of the world forgets about the project. An estimated 4,000 cards become lost in inactive wallets.",
      type: "dormant",
      importance: "medium"
    },
    {
      date: "March 2021",
      title: "The Great Rediscovery",
      text: "NFT 'archeologists' including Adam McBride rediscover Curio Cards while researching the history of NFTs. They find original 'vending machine' contracts still active with cards available for purchase. Renewed interest explodes. McBride interviews the co-founders and artists on his podcast, uncovering the full history.",
      type: "milestone",
      importance: "critical"
    },
    {
      date: "Mid 2021",
      title: "Wrapper Development",
      text: "Because Curio Cards predate the ERC-721 standard, a 'wrapper' is built to make them compatible with OpenSea and modern marketplaces. Card holders must wrap their old tokens to trade on current platforms. Some cards get locked in a faulty wrapper without an unwrap function.",
      type: "technical",
      importance: "high"
    },
    {
      date: "Summer 2021",
      title: "First Full Set Sale - 100 ETH",
      text: "The first full set of Curio Cards sells for 100 ETH (~$300,000). Adam McBride helps facilitate the sale. Only 15 people hold complete sets due to Card #26's supply of 111, which permanently limits complete sets.",
      type: "sale",
      importance: "high"
    },
    {
      date: "September 2021",
      title: "320 ETH Full Set Sale",
      text: "A complete set sells for 320 ETH ($1,034,377). In 2017, a full set cost $60. The exponential appreciation captures the attention of the traditional art world.",
      type: "sale",
      importance: "high"
    },
    {
      date: "October 1, 2021",
      title: "Christie's Auction - $1.27M",
      text: "A complete collection of 31 Curio Cards (including 17b) is sold by an anonymous seller for 393 ETH ($1,267,320) at Christie's Post-War to Present auction in New York. This marks the entry of Curio Cards into the traditional art establishment. Validates the project's historical significance.",
      type: "milestone",
      importance: "critical"
    },
    {
      date: "2021",
      title: "Arctic World Archive Preservation",
      text: "The Curio Cards collection is stored in The Arctic World Archive alongside 21 terabytes of GitHub open source code. The archive is designed to last 1,000 years, ensuring permanent preservation of the first art NFTs.",
      type: "milestone",
      importance: "high"
    },
    {
      date: "2021–2022",
      title: "XCOPY Revelation",
      text: "It's revealed that now-famous NFT artist XCOPY missed being included in the collection by a hair — he submitted his application via Google form too late and was denied. 'If XCOPY had been part of Curio Cards, it would have been a whole different story,' said NFT researcher Adam McBride.",
      type: "notable",
      importance: "medium"
    },
    {
      date: "Christmas 2021",
      title: "Curio Snowglobes",
      text: "The team releases Curio's Snowglobes — a 3D art collecting game featuring the Curio Cards raccoon mascot and remixes of the original set — as a reward to cardholders.",
      type: "community",
      importance: "low"
    },
    {
      date: "2022",
      title: "Curio DAO Formation",
      text: "The community forms the Curio DAO for collective governance and future direction. Uses tools like Coordinape for member rewards. Members participate through Twitter Spaces and Discord to guide the project's legacy.",
      type: "community",
      importance: "medium"
    },
    {
      date: "2022–Present",
      title: "Legacy & Recognition",
      text: "Curio Cards is widely recognized as the first art NFT collection on Ethereum. Referenced in the ERC-721 EIP standard that established NFTs. The community continues to preserve and celebrate the collection's historical significance. Notable collectors include 6529, Gary Vaynerchuk, DCLBlogger, Moderats, and FaZe Banks.",
      type: "legacy",
      importance: "high"
    },
  ],

  // ===================
  // ARTICLES
  // ===================
  
  articles: [
    {
      id: "origin-story",
      title: "The Origin Story: From Baseball Cards to Blockchain Art",
      date: "Featured Article",
      category: "History",
      featured: true,
      excerpt: "How a Bitcoin YouTuber's love of baseball cards and a chance meeting at a San Francisco meetup led to the creation of the first art NFTs on Ethereum.",
      content: `Thomas Hunt, known online as Mad Bitcoins, had always loved baseball trading cards. When he met software developer Travis Uhrig at a Bitcoin meetup in San Francisco, Hunt had a revelation: why not combine his love for cryptocurrency with his love for collecting? The idea was simple but revolutionary — create digital trading cards that lived on the blockchain, where ownership could be proven and art could be collected without intermediaries.

The pair organized a Bitcoin art show in San Francisco in 2016 called "Proof of Art." Among the exhibiting artists was Cryptograffiti, a local Bitcoin activist known for sticking crypto-themed stickers on bank ATMs. The success of the show confirmed their vision: digital art and blockchain were meant for each other.

They brought on Rhett Creighton, a cryptocurrency developer, as the technical muscle. Creighton originally suggested building their own version of Ethereum for the cards, but Uhrig pointed out this would leave the project orphaned on its own chain. They stayed on the public Ethereum blockchain — a decision that would prove prescient.

Over the following months, they recruited seven artists — Phneep, Cryptograffiti, Cryptopop, Robek World, Daniel Friedman, Marisol Vengas, and the mysterious Thoros of Myr — each bringing a unique artistic vision. On May 9, 2017, the first three cards went live. The art cost $1 each, with 100% going to the artists. Nobody knew it at the time, but they had just launched what would become the first art NFT collection on Ethereum.`
    },
    {
      id: "rediscovery",
      title: "The Great Rediscovery of 2021",
      date: "Featured Article",
      category: "History",
      featured: true,
      excerpt: "After years of dormancy, NFT archeologists stumbled upon the oldest art collection on Ethereum, sparking a renaissance.",
      content: `For nearly four years, Curio Cards existed in obscurity. The NFT market was virtually nonexistent. The cards traded for between 25 cents and a dollar — if they traded at all. The website went quiet, but crucially, the smart contracts remained active on Ethereum, silently holding their digital art.

In March 2021, as the NFT market exploded into mainstream consciousness, a group of NFT "archeologists" began digging through Ethereum's history. Adam McBride, who would become known for his exhaustive research into early NFT projects, was among those who rediscovered Curio Cards. They found that the original "vending machine" smart contracts were still active, even though the links had been removed from the website. Eager buyers found contracts that still had Curio Cards in them.

McBride embedded himself in the forming community, interviewing the co-founders and artists on his podcast. He helped facilitate the first full-set sale for 100 ETH. But even he made mistakes — he initially passed up on a group of hundreds of cards that would later be worth about $250,000. He called it an "epic and awesome" mistake, but shrugged it off. "The best thing about Curio Cards is I made friends," he said. "They're just really special people."

The rediscovery revealed fascinating details: the identity of Marisol Vengas (actually Max Infeld of Chico, California leading an art collective), the fact that XCOPY had nearly been included in the collection, and that Travis Uhrig himself didn't even have a complete set.`
    },
    {
      id: "17b-mystery",
      title: "The Mystery of Card 17b",
      date: "Featured Article",
      category: "Lore",
      featured: true,
      excerpt: "How a smart contract error created one of the most coveted digital artifacts in NFT history.",
      content: `Every great collection needs its legendary misprint, and Curio Cards has one of the best stories in all of NFTs. When Rhett Creighton was deploying the smart contract for Card #17 (UASF), something went wrong. The exact nature of the error has never been fully explained — even within the community, the technical details remain murky.

The erroneous contract was briefly live before anyone realized the mistake. During that window, one collector — who is actually still active in the Discord — managed to acquire an unknown number of 17b cards before the contract was disabled. Creighton had to redeploy a new, corrected contract for Card #17.

The misprint sparked debate within the community: should 17b be considered part of the canonical collection? After discussion, the community decided it should. Card 17b is now considered an integral part of a "full set," bringing the total to 31 cards. When the anonymous seller put up their complete collection at Christie's in October 2021, the lot included 17b — and the whole set sold for $1.27 million.

The 17b story captures something essential about early blockchain projects: these were experiments, built by passionate developers pushing the limits of new technology. Mistakes weren't just mistakes — they became part of the lore.`
    },
    {
      id: "christies",
      title: "From $60 to $1.27 Million: The Christie's Moment",
      date: "Featured Article",
      category: "Events",
      featured: true,
      excerpt: "When the world's most prestigious auction house sold a complete set of Curio Cards, it validated years of quiet persistence.",
      content: `In 2017, a complete set of Curio Cards could be purchased for approximately $60. On October 1, 2021, an anonymous seller consigned their complete set of 31 cards (including the legendary 17b misprint) to Christie's Post-War to Present auction in New York. It sold for 393 ETH — $1,267,320 at the time of sale.

The auction represented more than just a financial windfall. It was validation for a project that had spent years in obscurity, for artists who had been paid in single dollars for their work, and for a community that believed in the historical significance of being first.

Just weeks before the Christie's sale, another complete set had sold for 320 ETH ($1,034,377). The trajectory was clear: the market was recognizing not just the art, but the provenance. Curio Cards wasn't just an NFT collection — it was a historical artifact, the first of its kind, predating even CryptoPunks by several weeks.

The Christie's sale also highlighted the extreme rarity of complete sets. Because Card #26 (Education) has a supply of only 111, there can never be more than 111 complete sets. At the time of the sale, only 15 people held complete sets. The scarcity wasn't artificial or manufactured — it was the natural result of an artist named Daniel Friedman choosing a playful, decreasing supply pattern (333, 222, 111) for his three cards.`
    },
    {
      id: "first-animated-nft",
      title: "Card #23: The First Animated NFT on Ethereum",
      date: "Featured Article",
      category: "Cards",
      excerpt: "With only two frames and a lot of charm, The Barbarian made history as the first GIF on the Ethereum blockchain.",
      content: `Robek World had big ideas. Growing up collecting Japanese anime off dial-up internet, he understood the power of animation and visual storytelling. When he finally convinced the Curio Cards founders to let him contribute cards, he wanted to create elaborate, animated pixel art — RPG-inspired characters with fluid movement and detail.

But blockchain technology in 2017 wasn't ready for that. Robek was forced to simplify dramatically. Instead of complex animations, he created what the technology would allow: a two-frame GIF. Card #23, The Barbarian — depicting co-founder Rhett Creighton as a flexing, winking warrior — became the first animated NFT on the Ethereum blockchain.

Robek made the most of his constraints. The Barbarian's two frames show the character winking and flexing, creating a simple but charming loop. He chose the portraits of the three founders as his subjects: Thomas Hunt as The Wizard (#21), Travis Uhrig as The Bard (#22), and Creighton as The Barbarian (#23).

Strategically, Robek halved the supply of The Barbarian to 250 (compared to 500 for the other two), foreseeing that collectors would want all three cards in his set. The incentive worked — The Barbarian was the first card in the entire Curio Cards collection to sell out.

He even created a commercial for his three-card set, showcasing his dedication to the project. When his cards were released, Robek couldn't even buy them himself — a cruel irony for an early supporter who had created a gallery specifically to help the founders launch the project.`
    },
  ],

  // ===================
  // SETS
  // ===================
  
  sets: [
    { name: "Story Set", cards: [1,2,3,4,5,6,7,8,9,10], artist: "Phneep", description: "The first 10 cards tell the story of humanity's evolution into art creators: sustenance (1-3), building blocks of art (4-6), artistic creations (7-9), and the future (10)." },
    { name: "Bitcoin Propaganda", cards: [11,12,13], artist: "Cryptograffiti", description: "Rebranded bank logos that were once stickers on San Francisco ATMs. Goodbye UBS, MasterCard, and Citibank — hello Bitcoin." },
    { name: "Brand Mashups", cards: [14,15,16], artist: "Phneep", description: "Tongue-in-cheek cryptocurrency inserts into Coca-Cola, Wendy's, and Heineken logos. Witty commentary on marketing and consumerism." },
    { name: "Crypto Memes", cards: [17,"17b",18,19], artist: "Cryptopop", description: "The first dogs on Ethereum and crypto culture references. Includes the UASF card whose contract error spawned the legendary 17b." },
    { name: "Special (MadBitcoins)", cards: [20], artist: "Phneep", description: "The official Mad Bitcoins trading card — a portrait of co-founder Thomas Hunt. The first portrait on Ethereum." },
    { name: "RPG Founders", cards: [21,22,23], artist: "Robek World", description: "The three founders as RPG character archetypes. Includes the first animated NFT on Ethereum." },
    { name: "Hand-Drawn Patterns", cards: [24,25,26], artist: "Daniel Friedman", description: "Intricate freehand ink patterns with playfully decreasing supply (333→222→111). Brought physical art to digital space." },
    { name: "Subverted Fine Art", cards: [27,28,29], artist: "Marisol Vengas", description: "Collaborative physical artworks photographed digitally. Created through 'community algorithm' sessions at coffee shops." },
    { name: "Eclipse", cards: [30], artist: "Thoros of Myr", description: "The final card, released on the day of the Great American Eclipse. Created by the collection's most mysterious artist." },
  ],

  // ===================
  // KEY FACTS
  // ===================
  
  keyFacts: [
    "Curio Cards launched May 9, 2017 — six weeks before CryptoPunks",
    "Referenced in the ERC-721 NFT Standard (EIP-721)",
    "Total minted supply: 29,700 cards across 30 unique series + 17b",
    "Only 111 complete sets can ever exist (limited by Card #26 Education)",
    "100% of original sales revenue went directly to artists",
    "Stored in The Arctic World Archive, designed to last 1,000 years",
    "Card #23 (The Barbarian) is the first animated NFT on Ethereum",
    "Card #20 (MadBitcoins) is the first portrait on Ethereum",
    "Card #1 (Apples) is the first art NFT on Ethereum",
    "XCOPY submitted an application to be a Curio Cards artist but was too late",
    "A complete set sold for $1.27M at Christie's in October 2021",
    "Curio Cards were the first NFT project to use IPFS for artwork storage",
    "The Barbarian was the first card to sell out",
    "Cards originally cost $1 each",
    "An estimated 4,000 cards are lost in inactive wallets",
    "First collaborative NFT art (Marisol Vengas collective)",
    "Predates the ERC-721 standard, required wrapper for modern marketplaces",
  ],

  // ===================
  // METADATA
  // ===================
  
  metadata: {
    totalCards: 31,
    totalSupply: 29700,
    estimatedLost: 4000,
    launchDate: "2017-05-09",
    completionDate: "2017-08-21",
    maxCompleteSets: 111,
    rarestCard: 26,
    firstToSellOut: 23,
    contractType: "Pre-ERC-721",
    storageMethod: "IPFS (first to use)",
    blockchain: "Ethereum",
  }
};

// Export for use
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CURIO_DATA;
}
