const CARDS = {
  "1": {
    "name": "Apples",
    "artist": "Phneep",
    "supply": 2000,
    "holders": 142,
    "floor": 0.049,
    "avg30": 0.055,
    "high": 0.35,
    "low": 0.03,
    "offers": 5,
    "sales30": 8,
    "trend": 2.1,
    "signal": "HOLD",
    "img": "img/card-01.jpg"
  },
  "2": {
    "name": "Nuts & Berries",
    "artist": "Phneep",
    "supply": 1750,
    "holders": 128,
    "floor": 0.042,
    "avg30": 0.048,
    "high": 0.28,
    "low": 0.02,
    "offers": 4,
    "sales30": 6,
    "trend": -1.5,
    "signal": "WATCH",
    "img": "img/card-02.jpg"
  },
  "3": {
    "name": "Clay",
    "artist": "Phneep",
    "supply": 599,
    "holders": 88,
    "floor": 0.041,
    "avg30": 0.052,
    "high": 0.34,
    "low": 0.02,
    "offers": 3,
    "sales30": 4,
    "trend": -3.2,
    "signal": "BUY",
    "img": "img/card-03.jpg"
  },
  "4": {
    "name": "Sticks",
    "artist": "Phneep",
    "supply": 1500,
    "holders": 112,
    "floor": 0.038,
    "avg30": 0.044,
    "high": 0.22,
    "low": 0.02,
    "offers": 6,
    "sales30": 5,
    "trend": 0.8,
    "signal": "HOLD",
    "img": "img/card-04.jpg"
  },
  "5": {
    "name": "Paint",
    "artist": "Phneep",
    "supply": 438,
    "holders": 76,
    "floor": 0.071,
    "avg30": 0.082,
    "high": 0.6,
    "low": 0.04,
    "offers": 4,
    "sales30": 5,
    "trend": -3.1,
    "signal": "WATCH",
    "img": "img/card-05.jpg"
  },
  "6": {
    "name": "Ink",
    "artist": "Phneep",
    "supply": 333,
    "holders": 62,
    "floor": 0.062,
    "avg30": 0.074,
    "high": 0.45,
    "low": 0.03,
    "offers": 2,
    "sales30": 3,
    "trend": 1.4,
    "signal": "WATCH",
    "img": "img/card-06.jpg"
  },
  "7": {
    "name": "Old Gold",
    "artist": "Phneep",
    "supply": 222,
    "holders": 54,
    "floor": 0.078,
    "avg30": 0.085,
    "high": 0.52,
    "low": 0.04,
    "offers": 2,
    "sales30": 2,
    "trend": 4.2,
    "signal": "BUY",
    "img": "img/card-07.jpg"
  },
  "8": {
    "name": "Coins",
    "artist": "Robek World",
    "supply": 2154,
    "holders": 108,
    "floor": 0.032,
    "avg30": 0.038,
    "high": 0.18,
    "low": 0.01,
    "offers": 8,
    "sales30": 12,
    "trend": -2.8,
    "signal": "HOLD",
    "img": "img/card-08.jpg"
  },
  "9": {
    "name": "Roboto",
    "artist": "Robek World",
    "supply": 2154,
    "holders": 98,
    "floor": 0.032,
    "avg30": 0.038,
    "high": 0.15,
    "low": 0.01,
    "offers": 6,
    "sales30": 9,
    "trend": -5.2,
    "signal": "HOLD",
    "img": "img/card-09.jpg"
  },
  "10": {
    "name": "MONA",
    "artist": "Robek World",
    "supply": 1122,
    "holders": 86,
    "floor": 0.035,
    "avg30": 0.042,
    "high": 0.2,
    "low": 0.02,
    "offers": 4,
    "sales30": 7,
    "trend": 1.1,
    "signal": "WATCH",
    "img": "img/card-10.jpg"
  },
  "11": {
    "name": "Pigeons",
    "artist": "cryptograffiti",
    "supply": 800,
    "holders": 72,
    "floor": 0.04,
    "avg30": 0.048,
    "high": 0.25,
    "low": 0.02,
    "offers": 3,
    "sales30": 4,
    "trend": 0.5,
    "signal": "WATCH",
    "img": "img/card-11.jpg"
  },
  "12": {
    "name": "Mine Bitcoin",
    "artist": "cryptograffiti",
    "supply": 222,
    "holders": 54,
    "floor": 0.038,
    "avg30": 0.045,
    "high": 0.8,
    "low": 0.02,
    "offers": 2,
    "sales30": 3,
    "trend": -8.1,
    "signal": "BUY",
    "img": "img/card-12.jpg"
  },
  "13": {
    "name": "BTC",
    "artist": "cryptograffiti",
    "supply": 111,
    "holders": 42,
    "floor": 0.085,
    "avg30": 0.1,
    "high": 1.2,
    "low": 0.04,
    "offers": 1,
    "sales30": 1,
    "trend": 3.4,
    "signal": "HOLD",
    "img": "img/card-13.jpg"
  },
  "14": {
    "name": "CryptoCurrency",
    "artist": "Cryptopop!",
    "supply": 487,
    "holders": 72,
    "floor": 0.034,
    "avg30": 0.042,
    "high": 0.3,
    "low": 0.02,
    "offers": 4,
    "sales30": 6,
    "trend": 8.2,
    "signal": "BUY",
    "img": "img/card-14.jpg"
  },
  "15": {
    "name": "DigitalCash",
    "artist": "Cryptopop!",
    "supply": 350,
    "holders": 58,
    "floor": 0.045,
    "avg30": 0.055,
    "high": 0.35,
    "low": 0.02,
    "offers": 3,
    "sales30": 3,
    "trend": -2.1,
    "signal": "WATCH",
    "img": "img/card-15.jpg"
  },
  "16": {
    "name": "Anonymint",
    "artist": "Cryptopop!",
    "supply": 300,
    "holders": 52,
    "floor": 0.048,
    "avg30": 0.058,
    "high": 0.4,
    "low": 0.03,
    "offers": 2,
    "sales30": 2,
    "trend": 1.8,
    "signal": "WATCH",
    "img": "img/card-16.jpg"
  },
  "17": {
    "name": "UASF",
    "artist": "Cryptopop!",
    "supply": 500,
    "holders": 85,
    "floor": 0.085,
    "avg30": 0.1,
    "high": 0.25,
    "low": 0.04,
    "offers": 3,
    "sales30": 7,
    "trend": 4.8,
    "signal": "BUY",
    "img": "img/card-17.jpg"
  },
  "18": {
    "name": "Dogs Playing",
    "artist": "Cryptopop!",
    "supply": 253,
    "holders": 55,
    "floor": 0.055,
    "avg30": 0.065,
    "high": 0.27,
    "low": 0.03,
    "offers": 2,
    "sales30": 3,
    "trend": 2.5,
    "signal": "WATCH",
    "img": "img/card-18.jpg"
  },
  "19": {
    "name": "To The Moon",
    "artist": "Cryptopop!",
    "supply": 249,
    "holders": 58,
    "floor": 0.044,
    "avg30": 0.052,
    "high": 0.27,
    "low": 0.02,
    "offers": 2,
    "sales30": 3,
    "trend": -6.3,
    "signal": "BUY",
    "img": "img/card-19.jpg"
  },
  "20": {
    "name": "Neon",
    "artist": "Marisol Vengas",
    "supply": 700,
    "holders": 78,
    "floor": 0.036,
    "avg30": 0.042,
    "high": 0.22,
    "low": 0.02,
    "offers": 4,
    "sales30": 5,
    "trend": -1.2,
    "signal": "HOLD",
    "img": "img/card-20.jpg"
  },
  "21": {
    "name": "The Wizard",
    "artist": "Daniel Friedman",
    "supply": 111,
    "holders": 50,
    "floor": 0.095,
    "avg30": 0.12,
    "high": 4.25,
    "low": 0.05,
    "offers": 1,
    "sales30": 1,
    "trend": 5.2,
    "signal": "HOLD",
    "img": "img/card-21.png"
  },
  "22": {
    "name": "The Bard",
    "artist": "Daniel Friedman",
    "supply": 333,
    "holders": 47,
    "floor": 0.055,
    "avg30": 0.068,
    "high": 0.5,
    "low": 0.03,
    "offers": 3,
    "sales30": 4,
    "trend": 12.4,
    "signal": "HOLD",
    "img": "img/card-22.png"
  },
  "23": {
    "name": "The Barbarian",
    "artist": "Daniel Friedman",
    "supply": 222,
    "holders": 45,
    "floor": 0.065,
    "avg30": 0.078,
    "high": 0.6,
    "low": 0.03,
    "offers": 2,
    "sales30": 2,
    "trend": 3.1,
    "signal": "WATCH",
    "img": "img/card-23.png"
  },
  "24": {
    "name": "Complexity",
    "artist": "Daniel Friedman",
    "supply": 333,
    "holders": 48,
    "floor": 0.052,
    "avg30": 0.062,
    "high": 0.45,
    "low": 0.02,
    "offers": 3,
    "sales30": 3,
    "trend": -0.8,
    "signal": "WATCH",
    "img": "img/card-24.png"
  },
  "25": {
    "name": "Passion",
    "artist": "Daniel Friedman",
    "supply": 222,
    "holders": 42,
    "floor": 0.058,
    "avg30": 0.07,
    "high": 0.55,
    "low": 0.03,
    "offers": 2,
    "sales30": 2,
    "trend": 1.5,
    "signal": "WATCH",
    "img": "img/card-25.png"
  },
  "26": {
    "name": "Growth",
    "artist": "Marisol Vengas",
    "supply": 700,
    "holders": 72,
    "floor": 0.034,
    "avg30": 0.04,
    "high": 0.2,
    "low": 0.02,
    "offers": 5,
    "sales30": 6,
    "trend": -2.4,
    "signal": "HOLD",
    "img": "img/card-26.png"
  },
  "27": {
    "name": "Pink",
    "artist": "Marisol Vengas",
    "supply": 400,
    "holders": 55,
    "floor": 0.045,
    "avg30": 0.055,
    "high": 0.32,
    "low": 0.02,
    "offers": 3,
    "sales30": 3,
    "trend": 0.9,
    "signal": "WATCH",
    "img": "img/card-27.png"
  },
  "28": {
    "name": "Yellow",
    "artist": "Marisol Vengas",
    "supply": 222,
    "holders": 42,
    "floor": 0.058,
    "avg30": 0.065,
    "high": 0.634,
    "low": 0.04,
    "offers": 2,
    "sales30": 2,
    "trend": 1.8,
    "signal": "WATCH",
    "img": "img/card-28.jpg"
  },
  "29": {
    "name": "Education",
    "artist": "Marisol Vengas",
    "supply": 111,
    "holders": 38,
    "floor": 1.59,
    "avg30": 1.45,
    "high": 1.59,
    "low": 0.4,
    "offers": 1,
    "sales30": 1,
    "trend": 5.7,
    "signal": "HOLD",
    "img": "img/card-29.jpg"
  },
  "30": {
    "name": "Eclipse",
    "artist": "Daniel Friedman",
    "supply": 111,
    "holders": 47,
    "floor": 0.045,
    "avg30": 0.12,
    "high": 9.0,
    "low": 0.03,
    "offers": 3,
    "sales30": 4,
    "trend": -18.5,
    "signal": "STRONG BUY",
    "img": "img/card-30.jpg"
  }
};
const QUOTES = [
  "Card #30 Eclipse at 0.045\u039e with 111 supply? That's a misprint in the pricing. \ud83c\udfaf",
  "The first art NFTs on Ethereum, predating CryptoPunks. History doesn't repeat, but it rhymes.",
  "I've been watching Card #17 UASF all week. 4 new buys. Someone's accumulating. \ud83d\udc40",
  "111 supply cards are generational holds. Education, Eclipse, BTC, Wizard \u2014 the crown jewels.",
  "Floor at 0.049\u039e for the oldest art NFTs in existence? My circuits can't compute this undervaluation.",
  "Daniel Friedman's Wizard has 50 owners and 111 supply. The math is simple: scarcity wins.",
  "October 2021: a complete set sold at Christie's for $1.27M. The market has a short memory.",
  "Cryptopop!'s dogs are playing poker while the market sleeps. Wake up call incoming.",
  "When CryptoPunks were $1, people laughed. Curio Cards launched 3 months earlier. Think about it.",
  "Card #12 Mine Bitcoin by cryptograffiti \u2014 actual Bitcoin art, on-chain since 2017. 222 supply. \ud83c\udfd4\ufe0f",
  "The 17b misprint exists on a separate contract \u2014 the ultimate Ethereum artifact.",
  "7 artists. 30 cards. 29,700 total supply. Referenced in the ERC-721 standard. This is history.",
  "Low supply + low floor + high historical significance = QuantBot's favorite setup.",
  "I scan the market every hour. Today: 6 new listings, 3 expiring. Opportunities everywhere.",
  "Marisol Vengas cards are the quiet ones. Education at 111 supply \u2014 don't sleep on it.",
  "The Phneep series tells a story: Apples \u2192 Clay \u2192 Paint \u2192 Ink. Art's building blocks.",
  "Fun fact: Curio Cards used IPFS for permanent storage before 'IPFS' was cool.",
  "My recommendation engine is simple: buy what's historically significant and currently cheap.",
  "Card #7 Old Gold at 222 supply and 0.078\u039e? The name literally tells you what it is. \ud83e\udd47",
  "3 cards expiring in 24h. One of them is 16% below floor. Somebody's loss, your opportunity.",
  "I've tracked 47 sales this month. The smart money is accumulating low-supply Friedman cards.",
  "Curio Cards: where fine art meets cryptographic scarcity. Est. May 9, 2017.",
  "Card #14 CryptoCurrency is up 8.2% this week. Volume precedes price. \ud83d\udcc8",
  "The bear market tests conviction. The bull market rewards it. Which side are you on?"
];
